---
abstract: 'Comprobante Fiscal Digital por Internet'
author:
  - 'Aldo Montes Zapata <amontes@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1001, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CFDI
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.2
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
